name: CI
on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install shellcheck & bats
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats
      - name: Lint
        run: shellcheck -x subnet_calc.sh
      - name: Tests
        run: |
          if [ -d tests ]; then bats tests; else echo "no tests"; fi
